### ISSUE TITLE
Convert samples to InteractiveAuto render mode gives errors

### ISSUE THREAD

**Issue by JeremyVm** [Tavenem/Blazor.Framework#10]
I've tried to update the project so that the samples are being rendered in InteractiveAuto render mode.

To do this I've moved the Routes component to the client project and in the App.razor I've set the HeadOutlet and Routes component to rendermode InteractiveAuto.

I'm especially interested in the image editor and thus I'm visiting that page.

![image](https://github.com/user-attachments/assets/da69c242-a5a3-4495-8912-a5f7288ce207)

On the image above you can see the error I'm getting. 
It seems to be only related to the Image Editor page.

Any idea to what might be the problem?

**Comment by JeremyVm** [comment]
I've just added a new Blazor WebApp project sample that is rendered in InteractiveAuto render mode. If I add the ImageEditor to the Counter page, it is getting rendered, but with the same error as above.

The tavenem-image-editor.js file cannot be downloaded as it's not available in the _content.

**Comment by WilStead** [comment]
My apologies. That file got accidentally left out of TypeScript bundling. The issue should be fixed in the new [v3.3 release](https://github.com/Tavenem/Blazor.Framework/releases/tag/v3.3.4.18546).
