### ISSUE TITLE
Remove adding Tavenem framework CSS file from JS initialization

### ISSUE THREAD

**Issue by danielnutu** [Tavenem/Blazor.Framework#8]
Tavenem.Blazor.Framework.lib.module.js adds the framework CSS to the header and cancels any overwrites to CSS properties from my app's CSS.

Can't the framework CSS be added manually by the user/developer?

**Comment by WilStead** [comment]
You're absolutely right.

I added this to the JavaScript initializer to simplify the setup process, but the ability to customize CSS is critical and is impeded by the process. I've reverted to manual CSS inclusion in the latest release.
